### ISSUE TITLE
New Styles Needed

### ISSUE THREAD

**Issue by MyBaBB** [siwamsingh/todo-react-router-redux#3]
Hi, This is the first time I ever created an issue also.  I did some work for you,
as follows.  "git commit -m " added favicon and title, styled the EditList.jsx, adjusted header for xs: so that it didn't get bumped off , and I threw in some google fonts and styed all the words with Libre_Baskerville for appeal. Added some media queries for good customizations. and added xxs: to tailwind config"   I didn't work on the hamburger page or the login but I got it looking good for you.
I can turn it in when you assign it to me again.  thanks again for having something to do.
I will follow you on Linked in, You have a nice reputation.

**Comment by siwamsingh** [comment]
Thanks for making improvements in the repo . Since its just a practice projects you have done enough 👍. I am thinking of creating a new project if you want we can collaborate on that . 
Here is my discord id siwam_singh send me a friend request if you are interested.

**Comment by siwamsingh** [comment]
I am assigning this issue to you . Just make sure edit list part is also styled .
